#+--------------------------------------------------------------------+
#| config-dev.yml
#+--------------------------------------------------------------------+
#| Copyright DarkOverlordOfData (c) 2013
#+--------------------------------------------------------------------+
#|
#| This file is a part of Huginn
#|
#| Huginn is free software; you can copy, modify, and distribute
#| it under the terms of the MIT License
#|
#+--------------------------------------------------------------------+
#
# Development configuration
#
# Use with huginn serve --dev
#
name: "phaser console test"
description: "On, Hekyll! On, Jekyll! On Huginn and Muninn!"
url: http://localhost/
port: 0xd16a

source: ./template
destination: ./gh-pages/phaser-console

serve:
  - ./gh-pages
  - ../../darkoverlordofdata.github.io/master


plugins:
  - huginn-asset-bundler


asset_bundler:
  compress:
    js: false
    css: false
  base_path: /assets/
  shim: /phaser-console
  server_url: //cdn.darkoverlordofdata.com/
  remove_bundled: false
  dev: true
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'></script>\n"
    css: "<link rel='stylesheet' type='text/css' href='{{url}}' />\n"


